### ISSUE TITLE
recruit Vicki’s Diversity and Inclusion BAT to go through the BAT set-up process

### ISSUE THREAD

**Issue by jhibbets** [codeforamerica/bat-META#16]
For Neil

**Comment by jhibbets** [comment]
@tdooner How do I add Neil Planchon to the team / CfA org so I can assign this issue to him?

**Comment by tdooner** [comment]
@jhibbets I'll get back to you once I have the proper permissions to manage our github org. Then we can see if there is a way I can delegate permission to you. Otherwise, I'm afraid you'll probably have to send requests for that to me.

**Comment by jhibbets** [comment]
We are not going to ask Vicki to implement the D&I BAT for this process due to time constraints
