### ISSUE TITLE
Figure out how to add members to BAT repo's

### ISSUE THREAD

**Issue by jhibbets** [codeforamerica/bat-META#18]
From issue #16, "How do I add Neil Planchon to the team / CfA org so I can assign this issue to him?"

@tdooner was going to look into how we add members to BAT GitHub repo's

**Comment by tdooner** [comment]
@jhibbets I see that you are the admin of this repo, so you should be able to add collaborators to this repo for purposes of assigning the issue. Will that process work for this and other BATs?

**Comment by jhibbets** [comment]
@tdooner  yes, I figured this out last night, but then ran into this question: how does a person become part of the CfA organization?

This is my updated doucmenation for Step 1 D of the BAT frameowrk
GitHub repository 
* [ACTION] - NAC sponsor will create a new GitHub repository using the following naming convention: bat-[BAT_NAME]
* [ACTION] - NAC sponsor will create a new team:
** Select Settings from the repository menu
** Select Collaborators & teams from the left-hand menu
** Configure the new team by adding a team name bat-[BAT_NAME]-team more, an optional description, option parten team, and setting visibility to Visible
 ** Select the green Create Team button
* [ACTION] - NAC sponsor will add the new team to the repository
** Select Settings from the repository menu
** Select Collaborators & teams from the left-hand menu
** Under the Teams section, select the team you created above (bat-[BAT_NAME]-team ) from the Add a team: Select team drop-down menu
** Give the team Write permissions
* [ACTION] - NAC sponsor will add members to new team*
** Select Settings from the repository menu
** Select Collaborators & teams from the left-hand menu
** Under the Teams section, select the team name (with the number of members listed below)
** From the Discussions page, select Members from the top menu
** Use the green Add a member button and add a GitHub user ID or email address to add members to your team; assign them an appropriate role as-needed
** Note: Team members will need to be part of the Code for America organization

**Comment by jhibbets** [comment]
@tdooner I am unable to add / invite members that are not part of the CfA organization, see
[Uploading Screenshot from 2018-01-10 14-55-36.png...]

**Comment by tdooner** [comment]
(The screenshot upload didn't work)

I just looked through the github permission structure and didn't find any easy way to delegate the permission to add people to our organization. So perhaps we can designate a single point person who's responsible for adding BAT members to the specific teams / repos that are necessary. I'm happy to handle this for now and we can figure out how to automate it later. (Or if you have any ideas, let me know.)

**Comment by jhibbets** [comment]
@tdooner got it. I will update the framework with that additional step and if we find an easy way to do this, we'll act accordingly. thanks for looking into this.

**Comment by tdooner** [comment]
Sounds good. I did some google searching to see if a tool like Slackin (the slack auto-invite tool thing) existed for Github organizations, but couldn't find anything. Just send me people that need to be added to CfA and I'll get them added.
