### ISSUE TITLE
Automate BAT Framework steps as issues

### ISSUE THREAD

**Issue by jhibbets** [codeforamerica/bat-META#19]
Hi Tom,

I was wondering if you know of a way that we could automate the creation of issues based on the steps needs to spin-up a BAT. Much like many of the issues outlines in this repo.

The idea would be to have a template of issues that could be added to repo upon its creation. Thanks!

**Comment by tdooner** [comment]
@jhibbets Can you tell me more about what kind of issues/how many issues? I googled a bit for an easy way to do this but couldn't find anything. If possible I'd like to steer towards just doing this manually.

**Comment by jhibbets** [comment]
@tdooner I'm guessing about 15-18 tasks. In my head, I'd like to basically take all the actions from the BAT framework and deploy them as issues into a new BAT GitHub repo to make sure that no actions are overlooked during the onboarding process

**Comment by jhibbets** [comment]
@tdooner I ended up creating this - https://github.com/codeforamerica/brigade-action-teams/blob/master/issues_start.md which I think could work out well for this
