### ISSUE TITLE
Admin access and rename three existing BAT Google Groups

### ISSUE THREAD

**Issue by jhibbets** [codeforamerica/bat-META#20]
@tdooner - need some help here. We have three existing BAT Google Groups that don't meet the new naming convention and do not have a NAC member as an admin:
1) https://groups.google.com/a/codeforamerica.org/d/forum/knowledgebat rename: BAT-knowledge, admin Jill
2) https://groups.google.com/a/codeforamerica.org/d/forum/recognitionbat rename BAT-recognition admin Noel
3) https://groups.google.com/a/codeforamerica.org/d/forum/trustbat rename BAT-trust admin Vyki

PS - @GovInTrenches is the current owner of all the groups

**Comment by jhibbets** [comment]
@tdooner also, can you make me an admin on all those BAT Google Groups? Thanks!

**Comment by jhibbets** [comment]
@tdooner I see we also have the bat-meta group, can you make me an admin there as well? https://groups.google.com/a/codeforamerica.org/forum/#!forum/bat-meta

**Comment by jhibbets** [comment]
@tdooner checking in on this tasks, thanks

**Comment by jhibbets** [comment]
@tdooner this is the action from the BAT-META meeting on Jan 17 - thanks!

**Comment by tdooner** [comment]
Sorry, this fell through the cracks. I'll take care of this shortly.

**Comment by jhibbets** [comment]
@tdooner good timing, I've got the IFoundADog BAT coming your way soon.

**Comment by jhibbets** [comment]
Looking at these three groups, it looks like nac@ was added as a member, so I think you might need to add me through an invite to give admin access - @tdooner

**Comment by tdooner** [comment]
>    https://groups.google.com/a/codeforamerica.org/d/forum/knowledgebat rename: BAT-knowledge, admin Jill

done

>    https://groups.google.com/a/codeforamerica.org/d/forum/recognitionbat rename BAT-recognition admin Noel

done

>    https://groups.google.com/a/codeforamerica.org/d/forum/trustbat rename BAT-trust admin Vyki

done

> can you make me an admin on all those BAT Google Groups? Thanks!

done

> I see we also have the bat-meta group, can you make me an admin there as well?

done

**Comment by tdooner** [comment]
Let me know if there's anything else you need here!
