### ISSUE TITLE
Create Google Group: bat-meta@codeforamerica.org

### ISSUE THREAD

**Issue by jhibbets** [codeforamerica/bat-META#5]
NAC sponsor will request that Christopher Whitaker <christopher@codeforamerica.org> or a designated volunteer specialist will create a Google Group under the CfA infrastructure using the following naming convention: [BAT_NAME]-bat@codeforamerica.org

For @civicwhitaker

**Comment by jhibbets** [comment]
@govintrenches Can you create this Google Group please? Hopefully, I can add members?

**Comment by tdooner** [comment]
Done! I created one called `bat-meta@codeforamerica.org` (I put "bat" as a prefix so they are all next to each other alphabetically). @jhibbets: once you join it then I can give you admin privileges on it.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/129120/33963555-4d8e8d4a-e023-11e7-9e70-8001948c13ff.png">

**Comment by jhibbets** [comment]
@tdooner I accepted the invite, thank you
